- src: https://github.com/wcm-io-devops/ansible-conga-maven.git
  name: conga-maven
  scm: git
- src: https://github.com/wcm-io-devops/ansible-conga-facts.git
  name: conga-facts
  scm: git
- src: https://github.com/wcm-io-devops/ansible-conga-files.git
  name: conga-files
  scm: git
- src: https://github.com/wcm-io-devops/ansible-conga-aem-packages.git
  name: conga-aem-packages
  scm: git
- src: https://github.com/wcm-io-devops/ansible-aem-cms.git
  name: aem-cms
  scm: git
- src: https://github.com/wcm-io-devops/ansible-aem-service.git
  name: aem-service
  scm: git
- src: https://github.com/wcm-io-devops/ansible-conga-aem-cms.git
  name: conga-aem-cms
  scm: git
